---
# tasks file for roles/s4a.ida_rsync

- name: ensure reports dest dir is created
  file:
    dest: '{{ ida_rsync_dst_dir }}'
    state: directory
    owner: '{{ ida_rsync_runtime_user }}'
    group: '{{ ida_rsync_runtime_user }}'
    mode: '0755'
  tags: [config]

- name: copy WebDAV IDA rsync script
  copy: 
    dest: '{{ item.dest }}'
    src:  '{{ item.src }}'
    owner: root
    group: root
    mode: '0755'
  loop:
    - src: ida_rsync
      dest: /usr/local/bin/ida_rsync
    - src: webdav_ida_rclone
      dest: /usr/local/bin/webdav_ida_rclone
  tags: [config]

- name: install IDA rclone script cron job
  cron: 
    name: "rclone cron job for IDA publication in public file shares by WebDAV"
    state: present
    minute: '13'
    hour: '14'
    user: rfg
    job: "/usr/local/bin/webdav_ida_rclone"
    cron_file: webdav_ida_rsync
  tags: [config]

