---

- hosts: consumers
  become: yes

  roles:

  - role: tersmitten.timezone 
    tags: [ common, timezone ] 

  - role: s4a.logrotate      
    tags: [ common, logrotate ] 

  - role: s4a.tessdb          
    tags: [ tessdb ]

  - role: s4a.reports         
    tags: [ reports ]
 
