---

# Hosts where to mount a webdav file systems
- hosts: reflex
  become: yes
  roles:

  - role: s4a.new_ida
    new_ida_uninstall: no
    new_ida_runtime_user: '{{ cred_ida_runtime_user }}'
    new_ida_base_dir: /home/{{ cred_ida_runtime_user }}
    new_ida_virtual_env: /home/{{ cred_ida_runtime_user }}/stars4all
    new_ida_remote_user: '{{ cred_ida_runtime_user }}'
    new_ida_remote_host: '{{ cred_ida_remote_host }}'
    new_ida_remote_dir: '{{ cred_ida_remote_dir }}'
    new_ida_cloud_tag: IDA
    new_ida_cloud_dir: IDA

  