---

# Hosts where to mount a webdav file systems
- hosts: reflex
  become: yes
  roles:
  # With rclone, we don't need to mount a WebDAV Filesystem
  # - role: s4a.webdav
  #   webdav_runtime_user: '{{ cred_webdav_runtime_user }}'
  #   webdav_username:    '{{ cred_webdav_username }}'
  #   webdav_password:    '{{ cred_webdav_password }}'
  #   webdav_host_fqdn:   '{{ cred_webdav_host_fqdn }}'
  #   webdav_url:         'https://{{ webdav_host_fqdn }}/remote.php/dav/files/{{ webdav_username }}/'
  #   tags: [ webdav ]

  # OBSOLETE
  # - role: s4a.ida_rsync
  #   tags: [ ida ]
  #   ida_rsync_runtime_user: '{{ cred_webdav_runtime_user }}'
  #   ida_rsync_src_dir: /home/{{ cred_webdav_runtime_user }}/dbase/reports/IDA
  #   ida_rsync_dst_dir: /home/{{ cred_webdav_runtime_user }}/webdav

  - role: s4a.new_ida
    new_ida_uninstall: no
    new_ida_runtime_user: '{{ cred_ida_runtime_user }}'
    new_ida_base_dir: /home/{{ cred_ida_runtime_user }}
    new_ida_virtual_env: /home/{{ cred_ida_runtime_user }}/stars4all
    new_ida_remote_user: '{{ cred_ida_runtime_user }}'
    new_ida_remote_host: '{{ cred_ida_remote_host }}'
    new_ida_remote_dir: '{{ cred_ida_remote_dir }}'
    new_ida_cloud_tag: IDA
    new_ida_cloud_dir: IDA

  