---

# Hosts where to mount a webdav file systems
- hosts: reflex
  become: yes
  roles:
  - role: s4a.webdav
    webdav_runtime_user: '{{ cred_webdav_runtime_user }}'
    webdav_username:    '{{ cred_webdav_username }}'
    webdav_password:    '{{ cred_webdav_password }}'
    webdav_host_fqdn:   '{{ cred_webdav_host_fqdn }}'
    webdav_url:         'https://{{ webdav_host_fqdn }}/remote.php/dav/files/{{ webdav_username }}/'
    tags: [ webdav ]

  - role: s4a.ida_rsync
    tags: [ ida ]
    ida_rsync_runtime_user: '{{ cred_webdav_runtime_user }}'
    ida_rsync_src_dir: /home/{{ cred_webdav_runtime_user }}/dbase/reports/IDA
    ida_rsync_dst_dir: /home/{{ cred_webdav_runtime_user }}/webdav

  