---
# Migrates database from migration_src group to migration_dst group

- hosts: migration_dst
  become: yes
  tasks:
    
  - name: stops tessdb service on dest machine
    service: name=tessdb state=stopped
   

- hosts: migration_src
  become: yes
  vars:

    dst_user      : rfg
    dst_dbase_dir : /var/dbase
    dst_host      : calyx.hst.ucm.es

  tasks:

  - name: pauses tessdb on src machine
    command: /usr/local/bin/tessdb_pause

  # Make sure the pub ssh of src_user is in 
  # the authorised_keys of dst_user 
  - name: synchronizes database on dest machine
    become_user: '{{ tessdb_install_user }}'
    command: rsync -zavh {{ tessdb_dbase_dir }}/tess.db {{ dst_user }}@{{ dst_host }}:{{ dst_dbase_dir }}/tess.db

  # CUANDO ESTEMOS YA SEGUROS PARARLO MANUALMENTE CON:
  # - sudo service tessdb stop
  # - sudo systemctl disable tessdb.service
  - name: resumes tessdb on src machine
    command: /usr/local/bin/tessdb_resume

- hosts: migration_dst
  become: yes
  gather_facts: false

  tasks:

  - name: starts tessdb service on dst machine
    service: name=tessdb state=started
   
