---

# Hosts where Reports builder are installed
- hosts: reports
  become: yes

  roles:

  - role: s4a.logrotate      
    tags: [ common, logrotate ] 

  - role: s4a.reports    
    reports_tess_ida_logrotate_days: 365 
    reports_dbase_dir: /home/rfg/dbase  
    reports_user: rfg
    reports_remote_backup: no
    tags: [ reports ]
