---

# Hosts where MQTT consumers reside
- hosts: consumers
  become: yes

  roles:

  - role: tersmitten.timezone 
    tags: [ common, timezone ] 

  - role: s4a.logrotate      
    tags: [ common, logrotate ] 

  - role: s4a.tessdb          
    tags: [ tessdb ]

  - role: s4a.stats          
    tags: [ stats ]

# Hosts where Reports builder are installed
- hosts: reports
  become: yes

  roles:
  # A peticion de Sergio
  # - role: tersmitten.timezone 
  #   tags: [ common, timezone ] 

  - role: s4a.logrotate      
    tags: [ common, logrotate ] 

  - role: s4a.reports    
    reports_tess_ida_logrotate_days: 365   
    tags: [ reports ]
