---

# Hosts where MQTT consumers reside
- hosts: consumers
  become: yes
  vars:

    # This prefix for testing inbstallation in another root directory
    pfx: ''

  roles:

  - role: s4a.logrotate      
    tags: [ common, logrotate ] 

  - role: s4a.tessdb
    tessdb_venv_dir       : '{{pfx}}/opt/stars4all40'
    tessdb_dbase_dir      : '{{pfx}}/var/dbase'
    tessdb_log_dir        : '{{pfx}}/var/log'
    tessdb_etc_dir        : '{{pfx}}/etc/tessdb'
    tessdb_service_dir    : '{{pfx}}/etc/systemd/system'
    tessdb_runtime_user   : '{{ cred_tessdb_runtime_user }}'
    tessdb_log_rotate     : 365   
    tessdb_service_enabled: yes
    tags: [ tessdb ]
