---
# tasks file for roles/s4a.webdav

- include_vars: '{{ ansible_distribution }}.yml'
  tags: [install, config]

- import_tasks: install.yml
  tags: [install]

- import_tasks: config.yml
  tags: [config]
 
