---
# Default entries for the 
# /etc/tessdb/config configuration file (except username/password)
tessdb_config:
  tessdb: {}
  log:    {}
  dbase:  
    auth_filter      : no
    close_when_pause : yes
    location_filter  : no
  mqtt: 
    tess_blacklist: ['test5','ema0','ema1','ema3','pruebas2']
    broker:        'tcp:{{ cred_tessdb_broker }}:{{ cred_tessdb_port }}'
    username:      '{{ cred_tessdb_username }}'
    password:      '{{ cred_tessdb_password }}'
  filter:
    enabled : yes
    depth   : 7
