---
# Default entries for the 
# /etc/tessdb/config configuration file (except username/password)
tessdb_config:
  tessdb: {}
  log:    {}
  dbase:
    connection_string: '{{ cred_tessdb_connection_string }}'  
    auth_filter      : no
    close_when_pause : yes
    buffer_size      : 50
    zp_threshold     : 10
  mqtt: 
    client_id:      prod-tessdb
    tess_blacklist: 
      - test5
      - ema0
      - ema1
      - ema3
      - pruebas2
      - sqm-1738
      - Pru4c
      - Prub4c
      - Pru4cb
      - starsD1
      - Prueba
      - pruebas1
      - pruebas2
      - pruebas3
      - pruebas4 
      - pruebas5 
      - pruebas6
      - pruebas7
      - pruebas8
      - pruebas9
      - pruebas10
      - pruebas01
      - pruebas02
      - pruebas03
      - pruebas04
      - pruebas05
      - pruebas06
      - pruebas07
      - pruebas08
      - pruebas09
    broker:        'tcp:{{ cred_tessdb_broker }}:{{ cred_tessdb_port }}'
    username:      '{{ cred_tessdb_username }}'
    password:      '{{ cred_tessdb_password }}'
  filter:
    enabled : yes
    depth   : 7
    log_level: warn
