---
# tasks file for roles/nto.tessdb

- name: create tessdb config directory if does not exists
  file: >
    path=/etc/tessdb
    state=directory
    owner={{ tessdb_runtime_user }}
    group={{ tessdb_runtime_user }}
    mode=0755
  tags: [config]

- name: copy tessdb main configuration file
  template: >
    dest=/etc/tessdb/config
    src=config.j2
    owner={{ tessdb_runtime_user }}
    group={{ tessdb_runtime_user }}
    mode=0644
  notify: restart tessdb service
  tags: [config]

- name: create tessdb database directory if does not exists
  file: >
    path={{ tessdb_dbase_dir }}
    state=directory
    owner={{ tessdb_runtime_user }}
    group={{ tessdb_runtime_user }}
    mode=0755
  tags: [config]

- name: Manage the SELinux state of database directory
  sefcontext:
    target: '{{ tessdb_dbase_dir }}'
    ftype: d
    setype: var_log_t
    seuser: unconfined_u
    state: present
  register: tessdb_selinux_context
  when: tessdb_selinux_enabled
  tags: [config]

- name: Apply SELinux context changes
  command: restorecon -v {{ tessdb_dbase_dir | quote }}
  when: tessdb_selinux_enabled and tessdb_selinux_context is changed
  tags: [config]

# File owner for this logrotate spec should be root
# as discovered by manually running logrotate
- name: Patches tessdb logrotate
  template: >
    dest=/etc/logrotate_astro.d/tessdb
    src=logrotate.j2
    owner=root
    group=root
    mode=0644
  tags: [config]

- name: Patches tessdb.service to include a virtualenv
  template: >
    dest=/lib/systemd/system/tessdb.service
    src=tessdb.service.j2
    owner={{ tessdb_runtime_user }}
    group={{ tessdb_runtime_user }}
    mode=0644
  register: tessdb_systemd_changed
  tags: [config]

- name: systemd daemon reload  
  command: systemctl daemon-reload
  when: tessdb_systemd_changed is changed
  tags: [config]

- name: patches tess utility to use a virtualenv
  template: >
    dest=/usr/local/bin/tess
    src=tess.j2
    owner=root
    group=root
    mode=0755
  tags: [config]

- name: install environment file for virtualenv
  template: >
    dest=/etc/tessdb/tessdb.env
    src=tessdb.env.j2
    owner={{ tessdb_runtime_user }}
    group={{ tessdb_runtime_user }}
    mode=0644
  notify: restart tessdb service
  tags: [config]

- name: Touch the tess.db database file
  file:
    path: '{{ tessdb_dbase_dir }}/tess.db'
    state: touch
    owner: '{{ tessdb_runtime_user }}'
    group: '{{ tessdb_runtime_user }}'
    mode: '0644'
  tags: [config]
