---
# tasks file for roles/nto.tessdb

- name: Install system level needed packages
  package: 
    name :
    - git
    - logrotate
    - '{{ tessdb_sqlite_pkg }}'
    state: latest 


- name: install (as root) tessdb-server in a virtual environment
  pip:
    name               : tessdb-server
    virtualenv         : '{{ tessdb_venv_dir }}'
    virtualenv_command : '{{ tessdb_python3 }} -m venv'
    state              : latest
  notify: restart tessdb service

