---
# tasks file for roles/nto.tessdb

- name: Install needed packages
  package: 
    name={{ item }} 
    state=latest 
  with_items:
  - '{{ tessdb_sqlite }}'



# - name: Install twisted-mqtt from PyPi
#   pip: >
#     name={{ item.pkg }} 
#     state={{ item.state     | default('latest') }}
#     version={{ item.version | default(omit) }}
#   with_items:
#   - { pkg: twisted-mqtt, state: latest }
 

- name: Checkout twisted-mqtt from GitHub
  become: yes
  become_user: '{{ tessdb_install_user }}'
  git: 
    repo:   'https://github.com/astrorafael/twisted-mqtt.git' 
    dest:   '{{ tessdb_install_dir }}/twisted-mqtt'
    clone:  yes
    update: yes
    version: master
    accept_hostkey: yes
  notify: restart tessdb service

# - name: Install twisted-mqtt by setup.py
#   shell: python setup.py install
#   args:
#     chdir:  '{{ tessdb_install_dir }}/twisted-mqtt'


- name: Checkout tessdb from GitHub
  become: yes
  become_user: '{{ tessdb_install_user }}'
  git: 
    repo:   'https://github.com/STARS4ALL/tessdb.git' 
    dest:   '{{ tessdb_install_dir }}/tessdb'
    clone:  yes
    update: yes
    version: master
    accept_hostkey: yes
  notify: restart tessdb service


- name: Install tessdb by setup.py
  shell: python setup.py install
  args:
    chdir:  '{{ tessdb_install_dir }}/tessdb'

