---

- name: create new tessdb virtual env base directory {{ new_tdb_venv_dir }} if does not exists
  ansible.builtin.file: 
    path: '{{ new_tdb_venv_dir }}'
    state: directory
    owner: '{{ new_tdb_runtime_user }}'
    group: '{{ new_tdb_runtime_user }}'
    mode: '0755'

- name: create python virtual env using uv under {{new_tdb_uv}}/.venv
  ansible.builtin.command: '{{new_tdb_uv}} venv --python 3.12'
  become: yes
  become_user: '{{ new_tdb_runtime_user }}'
  args:
    chdir: '{{ new_tdb_venv_dir }}'
    creates: '{{ new_tdb_venv_dir }}/.venv'

- name: install/upgrade tessdb-server using uv
  ansible.builtin.command: '{{new_tdb_uv}} pip install -U tessdb-server'
  become: yes
  become_user: '{{ new_tdb_runtime_user }}'
  args:
    chdir: '{{ new_tdb_venv_dir }}'

- name: create {{ new_tdb_usr_local_bin }} if does not exists
  ansible.builtin.file: 
    path: '{{ new_tdb_usr_local_bin }}'
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create symbolic links
  when: false
  ansible.builtin.file:
    src: '{{ new_tdb_venv_dir }}/.venv/bin/{{ item }}'
    dest: '{{ new_tdb_usr_local_bin }}/{{ item }}'
    state: link
  loop:
    - tessdb_pause
    - tessdb_resume
    - tessdb_reload
