---

- name: Ensure tessdb.service is present and enabled
  #when: false
  ansible.builtin.systemd_service:
    name: tessdb.service
    state: started
    daemon-reload: true
    enabled: true

- name: Ensure tdbalarm.timer is present and enabled
  ansible.builtin.systemd_service:
    name: tdbalarm.timer
    state: started
    daemon-reload: true
    enabled: true

- name: Ensure tdbalarm.service is present and enabled
  ansible.builtin.systemd_service:
    name: tdbalarm.service
    state: started
    daemon-reload: true
    enabled: true

