---
# tasks file for s4a.nagios

- name: Copy NRPE global configuration file from template
  template: 
    src:  nrpe.cfg.j2
    dest: '{{ nagios_config_dir }}'
    owner: root
    group: root
    mode: '0644'
  notify: restart nrpe service

- name: copy NRPE configuration file for check_logfiles
  template: 
    src:  nrpe_check_logfiles.cfg.j2
    dest: '{{ nrpe_config_dir }}/nrpe_check_logfiles.cfg'
    owner: root
    group: root
    mode: '0644'

- name: create a state directory for check_logfiles
  file:
    path: '{{ check_logfiles_state_dir }}'
    state: directory
    mode: '0755'

- name: create a protocol directory for check_logfiles
  file:
    path: '{{ check_logfiles_protocol_dir }}'
    state: directory
    mode: '0755'

- name: create an additional nagios executables directory
  file:
    path: '{{ nagios_exec_dir }}'
    state: directory
    mode: '0755'

- name: create an additional nagios config directory
  file:
    path: '{{ nagios_config2_dir }}'
    state: directory
    mode: '0755'

- name: copy check_logfiles configuration file for tessdb
  template: 
    src:  check_logfiles.cfg.j2
    dest: '{{ nagios_config2_dir }}/'
    owner: root
    group: root
    mode: '0644'

- name: copy restart script file for tessdb
  copy: 
    src:  nagios_tessdb_restart
    dest: '{{ nagios_exec_dir }}'
    owner: root
    group: root
    mode: '0755'


