---
# tasks file for s4a.nagios

- name: Install NRPE and plugins
  package: 
    name : '{{ nagios_plugin_pkgs }}' 
    state: latest 
  tags: [install]


- name: Install check_logfiles needed Perl packages
  package: 
    name : '{{ check_logfile_prerrequiste_pkgs }}' 
    state: latest 
  tags: [install]


- name: Copy check_logfiles source code
  unarchive:
    src: check_logfiles-4.0.1.tar.gz
    dest:  '{{ tessdb_install_dir }}'
    owner: '{{ tessdb_install_user }}'
    group: '{{ tessdb_install_user }}'
    mode: '0755'

- name: configure check_logfiles Makefile
  become:  yes
  become_user: '{{ tessdb_install_user }}'
  shell: './configure'
  args:
    chdir:   '{{ tessdb_install_dir }}/check_logfiles-4.0.1'
    creates: '{{ tessdb_install_dir }}/check_logfiles-4.0.1/Makefile'
  ignore_errors: yes

- name: build check_logfiles
  become:  yes
  become_user: '{{ tessdb_install_user }}'
  shell: 'make'
  args:
    chdir:   '{{ tessdb_install_dir }}/check_logfiles-4.0.1'
    creates: '{{ tessdb_install_dir }}/check_logfiles-4.0.1/plugins-scripts/check_logfiles'
  ignore_errors: yes

- name: install check_logfiles
  shell: 'make install'
  args:
    chdir:   '{{ tessdb_install_dir }}/check_logfiles-4.0.1'
    creates: '/usr/local/nagios/libexec/check_logfiles'
  ignore_errors: yes
