---
# tasks file for roles/nto.reports

- name: copy remote backup script
  template: >
    dest=/usr/local/bin/tessdb_remote_backup
    src=tessdb_remote_backup.j2
    owner=root
    group=root
    mode=0755

- name: install tess daily remote backup cron job
  cron: 
    name     : "cron job for tess remote backup" 
    minute   : '{{ reports_src_min }}'
    hour     : '{{ reports_src_hour }}'
    user     : '{{ reports_user }}' 
    job      : "/usr/local/bin/tessdb_remote_backup {{ reports_src_user }} {{ reports_src_host }} {{ reports_src_dir }} {{ reports_dbase_dir }}"
    cron_file: tessdb_remote_backup
  