---
# tasks file for roles/nto.reports


- name: ensure reports dir is created
  file: >
    dest={{ item }}
    state=directory
    owner={{ reports_user }}
    group={{ reports_user }}
    mode=0755
  with_items:
  - '{{ reports_dbase_dir }}/reports'
  - '{{ reports_dbase_dir }}/reports/IDA'

- name: patched tess_ida script to use a virtualenv
  template: >
    dest=/usr/local/bin/{{ item }}
    src={{ item }}.j2
    owner=root
    group=root
    mode=0755
  with_items:
  - tess_ida

- name: copy additional SQL report files
  template: >
    dest=/usr/local/bin/{{ item }}
    src={{ item }}
    owner=root
    group=root
    mode=0755
  with_items:
  - tess_catalog.sh
  - tess_changelog.sh


- name: install tess daily cron jobs
  cron: >
    name="cron job for {{ item.name }}" 
    minute={{ item.minute }}
    hour={{ item.hour }}
    user={{ reports_user }} 
    job="/usr/local/bin/{{ item.name }}.sh {{ reports_dbase_dir }}/{{ item.dbase }} {{ reports_dbase_dir }}/{{ item.subdir }} {{ item.arg3 }}"
    cron_file={{ item.name }}
  with_items:
  - { name: tess_sunrise_sunset, hour:  9, minute: 00, dbase: tess.db,    subdir: reports, arg3: '' }
  - { name: tess_catalog,        hour:  9, minute: 05, dbase: tess.db,    subdir: reports, arg3: '' }
  - { name: tess_changelog,      hour:  9, minute: 30, dbase: tess.db,    subdir: reports, arg3: '' }
  - { name: tess_life_span,      hour: 10, minute: 00, dbase: tess.db-\*, subdir: reports, arg3: '' }
  - { name: tess_daily_summary,  hour: 10, minute: 15, dbase: tess.db-\*, subdir: reports, arg3: '' }
  - { name: tess_ida_bulk_dump,  hour: 12, minute: 45, dbase: tess.db-\*, subdir: reports/IDA, arg3: 'latest' }
  - { name: tess_bulk_dump,      hour: 13, minute: 15, dbase: tess.db-\*, subdir: reports, arg3: '' }


- name: install tess monthly cron jobs
  cron: >
    name="cron job for {{ item.name }}" 
    minute={{ item.minute }}
    hour={{ item.hour }}
    day=1
    user={{ reports_user }} 
    job="/usr/local/bin/{{ item.name }}.sh {{ reports_dbase_dir }}/{{ item.dbase }} {{ reports_dbase_dir }}/{{ item.subdir }} {{ item.arg3 }}"
    cron_file={{ item.name }}
  with_items: 
  - { name: tess_ida_monthly,  hour: 14, minute: 00, dbase: tess.db-\*, subdir: reports/IDA, arg3: 'previous' }
 
