---
# tasks file for roles/nto.reports


- name: ensure reports dir is created
  file: >
    dest={{ item }}
    state=directory
    owner={{ reports_user }}
    group={{ reports_user }}
    mode=0755
  with_items:
  - '{{ reports_dbase_dir }}'
  - '{{ reports_dbase_dir }}/reports'
  - '{{ reports_dbase_dir }}/reports/IDA'
  tags: [config]

- name: patches tess_ida to use a virtualenv
  template: >
    dest=/usr/local/bin/{{ item }}
    src={{ item }}.j2
    owner=root
    group=root
    mode=0755
  with_items:
  - tess_ida
  tags: [config]

- name: install tess_ida logrotate spec
  template: >
    dest=/etc/logrotate.d/tess_ida
    src=tess_ida_logrotate.j2
    owner=root
    group=root
    mode=0644
  tags: [config]

- name: copy additional SQL report files
  template: >
    dest=/usr/local/bin/{{ item }}
    src={{ item }}
    owner=root
    group=root
    mode=0755
  with_items:
  - tess_catalog.sh
  - tess_changelog.sh
  tags: [config]


- name: install tess daily cron jobs
  cron: >
    name="cron job for {{ item.name }}"
    state={{ item.state }}
    minute={{ item.minute }}
    hour={{ item.hour }}
    user={{ reports_user }} 
    job="/usr/local/bin/{{ item.name }}.sh {{ reports_dbase_dir }}/{{ item.dbase }} {{ reports_dbase_dir }}/{{ item.subdir }} {{ item.arg3 }} {{ item.redirect }}"
    cron_file={{ item.name }}
  with_items:
  - { name: tess_catalog,            state: present ,hour: 12, minute: 50, dbase: tess.db, subdir: reports, arg3: '', redirect: ''}
  - { name: tess_changelog,          state: present, hour: 13, minute: 00, dbase: tess.db, subdir: reports, arg3: '', redirect: ''}
  - { name: tess_life_span,          state: present, hour: 13, minute: 15, dbase: tess.db, subdir: reports, arg3: '', redirect: '' }
  - { name: tess_readings_unassigned,state: absent,  hour: 13, minute: 22, dbase: tess.db, subdir: reports, arg3: '', redirect: '' }
  - { name: tess_daily_summary,      state: present, hour: 13, minute: 30, dbase: tess.db, subdir: reports, arg3: '', redirect: '' }
  - { name: tess_ida_bulk_dump,      state: present, hour: 13, minute: 45, dbase: tess.db, subdir: reports/IDA, arg3: 'latest', redirect: '>>/var/log/tess_ida.log 2>&1' }
  - { name: tess_bulk_dump,          state: present, hour: 14, minute: 15, dbase: tess.db, subdir: reports, arg3: '', redirect: '' }
  tags: [config]


- name: install tess_ida cron job to run on 1st of each month
  cron: >
    name="cron job for {{ item.name }}"
    state={{ item.state }}
    minute={{ item.minute }}
    hour={{ item.hour }}
    day=1
    user={{ reports_user }} 
    job="/usr/local/bin/tess_ida_bulk_dump.sh {{ reports_dbase_dir }}/{{ item.dbase }} {{ reports_dbase_dir }}/{{ item.subdir }} {{ item.arg3 }} {{ item.redirect }}"
    cron_file={{ item.name }}
  with_items: 
  - { name: tess_ida_monthly,  state: present, hour: 15, minute: 00, dbase: tess.db, subdir: reports/IDA, arg3: 'previous', redirect: '>>/var/log/tess_ida.log 2>&1' }
  tags: [config]
 
 
