---
# tasks file for roles/s4a.reports

- name: Install system level needed packages
  package: 
    name : '{{ item }}' 
    state: latest 
  with_items:
  - git
  - '{{ reports_sqlite }}'
  tags: [install]

- name: install (as user) PyPi dependencies in a virtual environment
  become_user: '{{ reports_user }}'
  pip:
    name               : '{{ item }}'
    virtualenv         : '{{ reports_venv_dir }}'
    virtualenv_command : '{{ reports_python3 }} -m venv'
    state              : latest
  with_items:
  - pyephem
  - tabulate
  - pytz
  - jinja2
  tags: [install]

# We install it as root because it copies files to /usr/local/bin
- name: install (as root) PyPi tessdb-reports package in a virtual environment
  pip:
    name               : '{{ item }}'
    virtualenv         : '{{ reports_venv_dir }}'
    virtualenv_command : '{{ reports_python3 }} -m venv'
    state              : latest
  with_items:
  - tessdb-reports
  - tessdb-cmdline
  tags: [install]
