# ----------------
# Role: s4a.tessdb 
# ----------------

tessdb_install_user : rfg
tessdb_venv         : stars4all
tessdb_dbase_dir    : /var/dbase
tessdb_install_dir  : /home/rfg
tessdb_venv_dir     : /home/rfg/stars4all


# run time user
tessdb_runtime_user: rfg

tessdb_service_enabled : yes

# -------------------------
# Role: s4a.reports 
# -------------------------

reports_dbase_dir: /var/dbase
reports_user:       rfg
reports_python3:   /usr/bin/python3
reports_venv_dir:  /home/rfg/stars4all



