# -----------------
# Role: s4a.new_ida 
# -----------------

global_python: /usr/bin/python3

# ----------------
# Role: s4a.tessdb 
# ----------------


# ----------------
# Role: s4a.stats 
# ----------------

# run time user
stats_runtime_user: '{{ tessdb_runtime_user }}'
stats_dbase_dir:    '{{ tessdb_dbase_dir }}'
stats_venv_dir :    '{{ tessdb_venv_dir }}'
