---
# tasks file for roles/s4a.mosquitto

- name: Make sure mosquitto certificates directory exists
  file:
    path: /etc/pki/mosquitto
    state: directory
    mode: '0755'

- name: copy mosquitto {{ mosquitto_role }} certificates
  copy: 
    dest: '{{ item.dest }}'
    src: '{{ item.src }}'
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
    mode: '{{ item.mode }}'
  loop:
    - src: '{{ mosquitto_role }}.key'
      dest: /etc/pki/mosquitto/{{ mosquitto_role }}.key
      owner: mosquitto
      group: mosquitto
      mode: '0600'
    - src: '{{ mosquitto_role }}.crt'
      dest: /etc/pki/mosquitto/{{ mosquitto_role }}.crt
      owner: mosquitto
      group: mosquitto
      mode: '0644'
    - src: ca-bundle.crt
      dest: /etc/pki/mosquitto/ca-bundle.crt
      owner: mosquitto
      group: mosquitto
      mode: '0644'
  tags: [config]

- name: copy mosquitto configuration files
  template: 
    dest: '{{ item.dest }}'
    src: '{{ item.src }}'
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
    mode: '{{ item.mode }}'
  loop:
    - src: mosquitto.service.j2
      dest: /etc/systemd/system/mosquitto-{{ mosquitto_role }}.service
      owner: root
      group: root
      mode: '0644'
    - src: mosquitto.conf.j2
      dest: /etc/mosquitto/mosquitto-{{ mosquitto_role }}.conf
      owner: mosquitto
      group: mosquitto
      mode: '0644'
    - src: mosquitto.aclfile.j2
      dest: /etc/mosquitto/aclfile-{{ mosquitto_role }}
      owner: mosquitto
      group: mosquitto
      mode: '0640'
  notify: Restart mosquitto {{ mosquitto_role }}
  tags: [config]


- name: copy mosquitto {{ mosquitto_role }} password file
  copy: 
    dest: /etc/mosquitto/pwfile-{{ mosquitto_role }}
    src:  pwfile-{{ mosquitto_role }}
    owner: mosquitto
    group: mosquitto
    mode: '0640'
  notify: Reload mosquitto {{ mosquitto_role }}
  tags: [config]

