---
- name: Enable and make mosquitto-{{ mosquitto_role }} {{ mosquitto_service_state }}
  service:
    name: mosquitto-{{ mosquitto_role }}
    enabled: yes
    state: '{{ mosquitto_service_state }}'