---
# tasks file for roles/s4a.new_ida
- name: ensure logs & reports directories are created
  file:
    dest: '{{ item }}'
    state: directory
    owner: '{{ new_ida_runtime_user }}'
    group: '{{ new_ida_runtime_user }}'
    mode: '0755'
  loop:
    - '{{ new_ida_reports_dir }}'
    - '{{ new_ida_logs_dir }}'
  tags: [config]

- name: copy the underlying IDA generation script
  template: 
    dest: '{{ item.dest }}'
    src:  '{{ item.src }}'
    owner: root
    group: root
    mode: '0755'
  loop:
    - src: tess-ida.j2
      dest: '{{ new_ida_bin_dir }}/tess-ida' 
  tags: [config]


- name: copy the logrotate spec for the cron jobs
  template: 
    dest: /etc/logrotate.d/ida
    src:  ida-logrotate.j2
    owner: root
    group: root
    mode: '0644'
  tags: [config]


- name: make a soft link for various scripts to use in cron jobs
  file: 
    dest: '{{ item.dest }}'
    src:  '{{ item.src }}'
    owner: root
    group: root
    state: link
  loop:
    - src:  '{{ new_ida_virtual_env }}/bin/tessdb_remote_backup'
      dest: '{{ new_ida_bin_dir }}/tessdb_remote_backup'
    - src:  '{{ new_ida_virtual_env }}/bin/tess_ida_bulk_dump'
      dest: '{{ new_ida_bin_dir }}/tess_ida_bulk_dump'
    - src:  '{{ new_ida_virtual_env }}/bin/tess_ida_bulk_dump_all'
      dest: '{{ new_ida_bin_dir }}/tess_ida_bulk_dump_all'
    - src:  '{{ new_ida_virtual_env }}/bin/tess_ida_bulk_dump_selective'
      dest: '{{ new_ida_bin_dir }}/tess_ida_bulk_dump_selective'
    - src:  '{{ new_ida_virtual_env }}/bin/webdav_ida_rclone'
      dest: '{{ new_ida_bin_dir }}/webdav_ida_rclone'  
  tags: [config]


- name: install various cron jobs
  cron: 
    name: '{{ item.name }}'
    state: '{{ item.state }}'
    day: '{{ item.day }}'
    hour: '{{ item.hour }}'
    minute: '{{ item.minute }}'
    cron_file: '{{ item.cron_file }}'
    job: '{{ item.job }}'
    user: '{{ new_ida_runtime_user }}'
  tags: [config]
  loop:
    - name: "cron job for tessdb remote backup"
      cron_file: tessdb_daily_remote_backup
      state: "{{ new_ida_enable_cron_jobs | ternary('present', 'absent') }}"
      day: '*'
      hour: '12'
      minute: '15'
      job: '{{ new_ida_bin_dir }}/tessdb_remote_backup -u {{ new_ida_remote_user }} -s {{ new_ida_remote_host }} -i {{ new_ida_remote_dir }} -o {{ new_ida_database_dir }} -l {{ new_ida_logs_dir }}/ida_daily.log'

    - name: "cron job for tess_ida_bulk_dump"
      cron_file: ida_daily
      state: "{{ new_ida_enable_cron_jobs | ternary('present', 'absent') }}"
      day: '*'
      hour: '13'
      minute: '00'
      job: '{{ new_ida_bin_dir }}/tess_ida_bulk_dump -d {{ new_ida_database_dir }}/tess.db -o {{ new_ida_reports_dir }} -m latest -l {{ new_ida_logs_dir }}/ida_daily.log'

    - name: "cron job for tess_ida_monthly"
      cron_file: ida_monthly
      state: "{{ new_ida_enable_cron_jobs | ternary('present', 'absent') }}"
      day: '1'
      hour: '15'
      minute: '0'
      job: '{{ new_ida_bin_dir }}/tess_ida_bulk_dump -d {{ new_ida_database_dir }}/tess.db -o {{ new_ida_reports_dir }} -m previous -l {{ new_ida_logs_dir }}/ida_monthly.log'

    - name: "rclone cron job for IDA publication in public file shares by WebDAV"
      cron_file: ida_webdav_daily
      state: "{{ new_ida_enable_cron_jobs | ternary('present', 'absent') }}"
      day: '*'
      hour: '14'
      minute: '15'
      job: '{{ new_ida_bin_dir }}/webdav_ida_rclone -i {{ new_ida_reports_dir }} -o {{ new_ida_cloud_dir }} -t {{ new_ida_cloud_tag }} -l {{ new_ida_logs_dir }}/ida_daily.log'

    - name: "Selective regeneration of monthly IDA files after manual fix"
      cron_file: ida_bulk_dump_selective
      state: "{{ new_ida_enable_cron_jobs | ternary('present', 'absent') }}"
      day: '*'
      hour: '16'
      minute: '15'
      job: '{{ new_ida_bin_dir }}/tess_ida_bulk_dump_selective -d {{ new_ida_database_dir }}/tess.db -o {{ new_ida_reports_dir }} -r {{ new_ida_base_dir}}/regenerate.ida.d -l {{ new_ida_logs_dir }}/ida_fix.log'