---
# tasks file for roles/s4a.new_ida
- name: ensure logs & reports directories are created
  file:
    dest: '{{ item }}'
    state: directory
    owner: '{{ new_ida_runtime_user }}'
    group: '{{ new_ida_runtime_user }}'
    mode: '0755'
  loop:
    - '{{ new_ida_reports_dir }}'
    - '{{ new_ida_logs_dir }}'
  tags: [config]

- name: copy the underlying IDA generation script
  template: 
    dest: '{{ new_ida_bin_dir }}/{{ item.name }}'
    src:   generic-script.j2
    owner: root
    group: root
    mode: '0755'
  loop:
    - name: tess-ida
    - name: tess-geolist
  tags: [config]


- name: copy the logrotate spec for the cron jobs
  template: 
    dest: /etc/logrotate.d/ida
    src:  ida-logrotate.j2
    owner: root
    group: root
    mode: '0644'
  tags: [config]


- name: make a soft link for various scripts to use in cron jobs
  file: 
    dest: '{{ new_ida_bin_dir }}/{{ item.name }}'
    src:  '{{ new_ida_virtual_env }}/bin/{{ item.name }}'
    owner: root
    group: root
    state: link
  loop:
    - name: tess_ida_pipeline
    - name: tess_ida_bulk_dump_selective
    - name: tess_geolist.sh
  tags: [config]


- name: install various cron jobs
  cron: 
    name: '{{ item.name }}'
    state: '{{ item.state }}'
    day: '{{ item.day }}'
    hour: '{{ item.hour }}'
    minute: '{{ item.minute }}'
    cron_file: '{{ item.cron_file }}'
    job: '{{ item.job }}'
    user: '{{ new_ida_runtime_user }}'
  tags: [config]
  loop:

    - name: "cron job for IDA reports pipeline"
      cron_file: ida_daily
      state: "{{ new_ida_enable_cron_jobs | ternary('present', 'absent') }}"
      day: '*'
      hour: '12'
      minute: '01'
      job: '{{ new_ida_bin_dir }}/tess_ida_pipeline -s {{ new_ida_remote_host }} -u {{ new_ida_remote_user }} -d {{ new_ida_remote_dir }} -o {{ new_ida_database_dir }} -m latest -i {{ new_ida_reports_dir }} -w {{ new_ida_cloud_dir }} -l {{ new_ida_logs_dir }}/ida_daily.log'


    - name: "cron job for tess_geolist.sh"
      cron_file: tess_geolist
      state: "{{ new_ida_enable_cron_jobs | ternary('present', 'absent') }}"
      day: '*'
      hour: '20'
      minute: '00'
      job: '{{ new_ida_bin_dir }}/tess_geolist.sh -d {{ new_ida_database_dir }}/tess.db -o {{ new_ida_reports_dir }} -l {{ new_ida_logs_dir }}/tess_geolist.log'

    
    - name: "cron job for end of month IDA pipeline"
      cron_file: ida_monthly
      state: "{{ new_ida_enable_cron_jobs | ternary('present', 'absent') }}"
      day: '1'
      hour: '15'
      minute: '0'
      job: '{{ new_ida_bin_dir }}/tess_ida_pipeline -p 3 -s {{ new_ida_remote_host }} -u {{ new_ida_remote_user }} -d {{ new_ida_remote_dir }} -o {{ new_ida_database_dir }} -m previous -i {{ new_ida_reports_dir }} -w {{ new_ida_cloud_dir }} -l {{ new_ida_logs_dir }}/ida_monthly.log'

   
    - name: "Selective regeneration of monthly IDA files after manual fix"
      cron_file: ida_bulk_dump_selective
      state: "{{ new_ida_enable_cron_jobs | ternary('present', 'absent') }}"
      day: '*'
      hour: '16'
      minute: '15'
      job: '{{ new_ida_bin_dir }}/tess_ida_bulk_dump_selective -d {{ new_ida_database_dir }}/tess.db -o {{ new_ida_reports_dir }} -r {{ new_ida_base_dir}}/regenerate.ida.d -l {{ new_ida_logs_dir }}/ida_fix.log'