---
# tasks file for roles/s4a.new_ida

- name: Install system level needed packages
  package: 
    name :
    - git
    - '{{ new_ida_sqlite }}'
    - '{{ new_ida_crond }}'
    - gcc
    #- python3-devel
    #- python-pip
    - logrotate
    state: latest 
  tags: [install]

# We install it as root because it copies files to /usr/local/bin
- name: install tessdb-reports in a virtual environment
  become_user: '{{ new_ida_runtime_user }}'
  pip:
    name               : git+http://github.com/STARS4ALL/tessdb-reports@main
    virtualenv         : '{{ new_ida_virtual_env }}'
    virtualenv_command : '{{ global_python }} -m venv'
    state              : latest
  tags: [install]
