---
# tasks file for roles/s4a.new_ida

- include_vars: main.yml
  tags: [install, config]

- include_vars: '{{ ansible_distribution }}.yml'
  tags: [install, config]

- import_tasks: install.yml
  tags: [install]

- import_tasks: config.yml
  tags: [config]
 
